# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='Sample', max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
