# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveyrecord_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrecord',
            name='bill_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bill Number'),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile'),
        ),
    ]
