# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20160120_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrecord',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
