# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_surveyrecord_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='surveyrecord',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
