# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrecord',
            name='answers',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
