# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20160120_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
