# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Option text')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('ques_type', models.CharField(choices=[(b'yn', b'Yes or No'), (b'sa', b'Short Answer'), (b'mcsa', b'Multi Choice(Single Answer)'), (b'ra', b'Rating'), (b'mcma', b'Multi Choice(Multiple Answer)')], max_length=150, verbose_name='Ques Type')),
                ('options', models.ManyToManyField(to='questions.Option')),
            ],
        ),
    ]
