# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[(b'yn', b'Yes or No'), (b'sa', b'Short Answer'), (b'mcsa', b'Multi Choice(Single Answer)'), (b'ra', b'Rating'), (b'mcma', b'Multi Choice(Multiple Answer)')], default=b'yn', max_length=150, verbose_name='Ques Type'),
        ),
    ]
